urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns("",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += patterns('',
        url('^i18n/$', 'django.views.i18n.set_language', name='set_language'),
    )

urlpatterns += patterns('',
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    #url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    (r'^api/bc/', include('phookit.bookingcalendar.api.urls')),
    # The availability page does not use mezzanine so needs to be here!
    (r'^availability/', include('phookit.bookingcalendar.urls')),
    (r'^contact/', include('contact_form.urls')),
    (r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

phookit/bookingcalendar/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save 


"""
Available : Time is available to book
Reserved : Time has been ordered but not fully booked (Not paid for)
Booked : Time has been booked and paid for.
"""
BOOKING_STATUS_CHOICES = (
    ('Available', 'Available'),
    ('Reserved',  'Reserved'),
    ('Booked',    'Booked'),
    ('Cancelled',    'Cancelled'),
)

class Booking(models.Model):
    start = models.DateField()
    end = models.DateField()
    name = models.CharField(max_length=1024)
    email = models.EmailField(null = True, blank = True)
    tel = models.CharField(max_length=32)

    info = models.TextField(max_length=1024, null = True, blank = True)
    status = models.CharField(choices=BOOKING_STATUS_CHOICES, default=BOOKING_STATUS_CHOICES[1][0], max_length=20)

    class Meta:
        ordering = ("start",)

    def __str__(self):
        return "%s : %s : %s->%s" % (self.name, self.status, self.start, self.end)

 
class BookingPrice(models.Model):
    start = models.DateField()
    end = models.DateField()
    price = models.CharField(max_length=10)

    class Meta:
        ordering = ("start",)

    def __str__(self):
        return "%s -> %s : %s" % (self.start, self.end, self.price)

theme/baytreecottage/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from mezzanine.core.fields import FileField, RichTextField
from mezzanine.core.models import RichText, Orderable, Slugged
from mezzanine.pages.models import Page
from mezzanine.utils.models import upload_to


class HomePage(Page, RichText):
    change_over_day = models.CharField(max_length=32)

    class Meta:
        verbose_name = _("Home Page")
        verbose_name_plural = _("Home Pages")

        
class Slide(Orderable):
    '''
    A slide in a slider connected to a HomePage
    '''
    homepage = models.ForeignKey(HomePage, related_name="slides")
    image = FileField(verbose_name=_("Image"),
        upload_to=upload_to("theme.Slide.image", "slider"),
        format="Image", max_length=255, null=True, blank=True)
    caption = models.CharField(max_length=64, null=True, blank=True)
    text_colour = models.CharField(max_length=15, default='#ffffff', null=True, blank=True, verbose_name="Text Colour")


class Statement(Orderable, RichText):
    '''
    Statement on a HomePage
    '''
    homepage = models.ForeignKey(HomePage, related_name="statements")
    title = models.CharField(max_length=200, null=True, blank=True)
    image = FileField(verbose_name=_("Image"),
        upload_to=upload_to("theme.Statement.image", "statement"),
        format="Image", max_length=255, null=True, blank=True)
    image_align = models.CharField(max_length=5,
                                   choices=( ('left', 'Left'),('right', 'Right') ),
                                   default='left')        

theme/baytreecottage/templates/contact_form/contact_form.html
{% extends "base.html" %}
{% load i18n mezzanine_tags pages_tags %}

{% block content %}
    <div class="section"> 
        <div class="container">
          <div class="row"> 

            <h1>{% trans "Contact Form" %}</h1>
            <p>Please fill in the form below to book the cottage or for any other enquiries. Alternatively you can call Carol on <a href="tel:{{ settings.ADDRESS_MOBILE_NUMBER }}">{{ settings.ADDRESS_MOBILE_NUMBER }}</a> or <a href="tel:{{ settings.ADDRESS_OTHER_NUMBER }}">{{ settings.ADDRESS_OTHER_NUMBER }}</a></p>
            <form id="contact-form" action="" method="post">{% csrf_token %}
              <div>
                  <label for="id_name">
                      <span>Name:</span>
                      <input id="id_name" maxlength="100" name="name" placeholder="Your name (required)" type="text" tabindex="1" required autofocus>
                  </label>
              </div>
              <div>
                  <label for="id_email">
                      <span>Email:</span>
                      <input id="id_email" maxlength="200" name="email" placeholder="Email address (required)" type="email" tabindex="2" required>
                  </label>
              </div>
              <div>
                  <label>
                      <span>Your Message:</span>
                      <textarea id="id_body" name="body" rows="10" placeholder="Enter your message (required)" tabindex="3" required></textarea>
                  </label>
              </div>
              <div>
                  <button name="submit" type="submit" id="contact-submit">Send Email</button>
              </div>
            </form>

        </div>
      </div>
    </div>
      {% endblock %}

theme/baytreecottage/templates/contact_form/contact_form_sent.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <p>{% trans "Thank you! Your message was sent successfully." %}</p>
{% endblock %}